name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2.0.1
        id: pnpm-install
        if: ${{ steps.release.outputs.releases_created }}
        name: Install pnpm
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        if: ${{ steps.release.outputs.releases_created }}
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        if: ${{ steps.release.outputs.releases_created }}
        run: rm -rf node_modules && pnpm i --frozen-lockfile

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        if: ${{ steps.release.outputs.releases_created }}
        uses: changesets/action@v1
        with:
          # This expects you to have a script which does a build for your packages and calls changeset publish
          publish: pnpm publish-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
